package com.example.saicko.funfacts;

import java.util.Random;

/**
 * Created by Sasa on 18.2.2015..
 */
public class FactBook {

    public String[] mFacts = {
            "A creep is a metallurgical term for when something that is normally very strong bends because of gravity. This happens to many metals at high temperatures, where they won't melt but they will creep.",
            "Ants stretch when they wake up in the morning.",
            "Ostriches can run faster than horses.",
            "Olympic gold medals are actually made mostly of silver.",
            "You are born with 300 bones; by the time you are an adult you will have 206.",
            "It takes about 8 minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The state of Florida is bigger than England.",
            "Some penguins can leap 2-3 meters out of the water.",
            "On average, it takes 66 days to form a new habit.",
            "Mammoths still walked the earth when the Great Pyramid was being built.",
            "Lightning strikes the earth about 8 million times a day.",
            "Contrary to popular belief, suicide rates during the Christmas holiday are low. The highest rates are during the spring.",
            "Christmas trees have been sold in the U.S. since 1850.",
            "Norwegian scientists have hypothesized that Rudolph's red nose is probably the result of a parasitic infection of his respiratory system.",
            "Christmas trees usually grow for about 15 years before they are sold.",
            "Alabama was the first state in the United States to officially recognize Christmas in 1836.",
            "The country code for Russia is “007'ł.",
            "Angel Falls in Venezuela is the world's highest waterfall, at 3,212 feet (979 m).",
            "A crocodiles tongue is attached to the roof of its mouth.",
            "Great Britain was the first county to issue postage stamps. Hence, the postage stamps of Britain are the only stamps in the world not to bear the name of the country of origin. However, every stamp carries a relief image or a silhouette of the monarch's head instead.",
            "Your stomach needs to produce a new layer of mucus every two weeks or it would digest itself.",
            "Most dust particles in your house are made from dead skin!",
            "There are 1,792 steps in the Eiffel Tower",
            "Koalas never drink water. They get fluids from the eucalyptus leaves they eat.",
            "Arabic numerals are not really Arabic; they were created in India.",
            "EMI stands for ` Electrical and Musical Instruments'.",
            "Elephants only sleep for two hours each day.",
            "In space, astronauts cannot cry, because there is no gravity, so the tears can't flow.",
            "Hara kiri is an impolite way of saying the Japanese word seppuku which means, literally, belly splitting.",
            "An Olympic gold medal must contain 92.5 percent silver",
            "There are 240 dots on an arcade Pac-Man game",
            "Every time you lick a stamp you consume 1/10 of a calorie.",
            "The first female guest host of “Saturday Night Live” was Candace Bergen.",
            "A man's beard grows fastest when he anticipates sex.",
            "King Louis XIX ruled France for 15 minutes.",
            "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
            "If a frog's mouth is held open for too long the frog will suffocate.",
            "A duck has three eyelids.",
            "In most watch advertisements the time displayed on a watch is 10:10.",
            "An American urologist bought Napoleon's penis for $40,000.",
            "Antarctica is the only continent that does not have land areas below sea level.",
            "Jimmy Carter was the first U.S. President to be born in a hospital.",
            "Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning containing arsenic.",
            "160 cars can drive side by side on the Monumental Axis in Brazil, the world's widest road.",
            "Mongolia is the largest landlocked country.",
            "Maine is the only state (in USA) whose name is just one syllable.",
            "Carnivorous animals will not eat another animal that has been hit by a lightning strike.",
            "Mr. Rogers was an ordained minister.",
            "In 1825, Upper Peru became Bolivia.",
            "The highest point in Pennsylvania is lower than the lowest point in Colorado.",
            "The Michelin man is known as Mr. Bib. His name was Bibendum in the company's first ads in 1896.",
            "Gabriel, Michael, and Lucifer are the only angels named in the Bible.",
            "You're born with 300 bones, but by the time you become an adult, you only have 206.",
            "Jamaica has the most churches per square mile than any other country in the world.",
            "In 1859, 24 rabbits were released in Austrailia. Within six years the population grew to 2 million.",
            "When the Titanic sank, 2228 people were on it. Only 706 survived.",
            "The electric chair was invented by a dentist.",
            "The plastic things on the end of shoelaces are called aglets.",
            "A hippo can open its mouth wide enough to fit a four foot tall child inside.",
            "Butterflies cannot fly if their body temperature is less than 86 degrees.",
            "Clouds fly higher during the day than the night.",
            "Between 1902 and 1907 the same tiger killed 436 people in India.",
            "Many butterflies can taste with their feet to find out whether the leaf they sit on is good to lay eggs on to be their caterpillars' food or not.",
            "The human brain is about 75% water.",
            "A group of kangaroos is called a mob.",
            "Ever wonder where the term Work Smarter'¦Not Harder originated? Allan F. Mogensen, the creator of Work Simplification, coined the phrase in the 1930'˛s. The 1990'˛s equivalent term is probably Business Process Reengineering.",
            "A woodchuck breathes only 10 times in hibernation.",
            "The Declaration of Independence was written on hemp (marijuana) paper.",
            "The longest one-syllable word in the English language is “screeched.”",
            "Michigan was the first state to have roadside picnic tables.",
            "$283,200 is the absolute highest amount of money you can win on Jeopardy.",
            "Most lipstick contains fish scales.",
            "Possums have one of the shortest pregnancies at 16 days. The shortest human pregnancy to produce a healthy baby was 22 weeks, 6 days '” the baby was the length of a ballpoint pen.",
            "Frog-eating bats identify edible from poisonous frogs by listening to the mating calls of male frogs. Frogs counter by hiding and using short, difficult to locate calls.",
            "Broccoli and cauliflower are the only vegetables that are flowers.",
            "A Boeing 747s wingspan is longer than the Wright brother's first flight.",
            "Dogs and cats consume over $11 billion worth of pet food a year",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "Jim Morrison, of the 60'˛s rock group The Doors, was the first rock star to be arrested on stage.",
            "You share your birthday with at least 9 million other people in the world.",
            "In a tradition dating to the begining of the Westminster system of government, the bench in the middle of a Westminster parliarment is two and a half sword lengths long. This was so the government and oppositon couldn't have a go at each other if it all got a bit heated",
            "If you attempted to count the stars in a galaxy at a rate of one every second it would take around 3,000 years to count them all.",
            "In England, the Speaker of the House is not allowed to speak.",
            "In the last 4000 years no new animals have been domesticated.",
            "Hannibal had only one eye after getting a disease while attacking Rome.",
            "An ostrich's eye is bigger than its brain.",
            "The human heart creates enough pressure in the bloodstream to squirt blood 30 feet.",
            "In Italy, 17 is considered an unlucky number. In Japan, 4 is considered an unlucky number.",
            "The world's longest snake (by reliable documentation) is the reticulated python, with a maximum length of, perhaps, 30 feet.",
            "Ramses brand condom is named after the great pharaoh Ramses II who fathered over 160 children.",
            "In the United States, more Frisbee discs are sold each year than baseballs, basketballs, and footballs combined.",
            "A chameleon's tongue is twice the length of its body.",
            "In Alaska it is illegal to shoot at a moose from the window of an airplane or other flying vehicle.",
            "The average garden variety caterpillar has 248 muscles in its head.",
            "Anise is the scent on the artificial rabbit that is used in greyhound races.",
            "Ernest Vincent Wright wrote a 50,000 word novel without any word containing “e.”",
            "The average person's left hand does 56% of the typing.",
            "At the height of its power in 400 BC, the Greek city of Sparta had 25,000 citizens and 500,000 slaves.",
            "It is believed that Shakespeare was 46 around the time that the King James Version of the Bible was written. In Psalms 46, the 46th word from the first word is shake and the 46th word from the last word is spear.",
            "The cruise liner Queen Elizabeth II moves only six inches for each gallon of diesel that it burns.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "It's estimated that at any one time around 0.7% of the world's population is drunk.",
            "Like fingerprints, everyone's tongue print is different!",
            "Everyday, more money is printed for Monopoly sets than for the U.S. Treasury.",
            "There is a hotel in Sweden built entirely out of ice; it is rebuilt every year.",
            "Intelligent people have more zinc and copper in their hair.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "One in fourteen women in America is a natural blonde. Only one in sixteen men is.",
            "The venom of the Australian Brown Snake is so powerful only 1/14,000th of an ounce is enough to kill a human.",
            "Ballroom dancing is a major at Brigham University.",
            "The human feet perspire half a pint of fluid a day",
            "In every episode of “Seinfeld” there is a Superman picture or reference somewhere.",
            "There is a city in Norway called “Hell”",
            "A standard grave is 7'8 x 3'2 x 6.",
            "Tina Turner's real name is Annie Mae Bullock.",
            "Babies are born without knee caps. They don't appear until the child reaches 2-6 years of age.",
            "You is the second most spoken English word",
            "The first novel ever written on a typewriter is Tom Sawyer.",
            "Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.",
            "According to Genesis 1:20-22, the chicken came before the egg.",
            "Arachibutyrophobia is the fear of peanut butter sticking to the roof of your mouth.",
            "If you put a drop of liquor on a scorpion, it will instantly go mad and sting itself to death.",
            "The average human blinks their eyes 6,205,000 times each year.",
            "US Dollar bills are made out of cotton and linen.",
            "The glue on Israeli postage is certified kosher.",
            "98% of all murders and rapes are by a close family member or friend of the victim.",
            "The February of 1865 is the only month in recorded history not to have a full moon.",
            "Some people say that when the black bands on the Woolybear caterpillar are wide, a cold winter is coming.",
            "There are more donut shops in Canada per capita than any other country.",
            "Termites outweigh humans by almost ten to one.",
            "John Adams, Thomas Jefferson, and James Monroe died on July 4th.",
            "Construction workers hard hats were first invented and used in the building of the Hoover Dam in 1933.",
            "Groaking is to watch people eating in hopes that they will offer you some.",
            "Right handed people live, on average, nine years longer than left handed people do.",
            "It can take as long as 4 hours to hard-boil an ostrich egg.",
            "14% of all facts and statistics are made up and 27% of people know that fact.",
            "The volume of the earth's moon is the same as the volume of the Pacific Ocean.",
            "The cheetah is the only cat that can't retract its claws.",
            "A rat can last longer without water than a camel.",
            "A jumbo jet uses 4,000 gallons of fuel to take off.",
            "In the Philippines, MABUHAY means Hello.",
            "Each year there is one ton of cement poured for each man, woman and child in the world.",
            "An ant always falls over on its right side when intoxicated.",
            "The most common name in Italy is Mario Rossi.",
            "It is impossible to lick your elbow.",
            "Sailfish can leap out of the water and into the air at a speed of 50 miles (81 km) per hour.",
            "A “2 by 4'ł is really 1 1/2 by 3 1/2.",
            "If you look carefully at the picture of Mona Lisa, you will notice a bridge in the background.",
            "The only real person to be a PEZ head was Betsy Ross.",
            "Each year there is one ton of cement poured for each man woman and child in the world.",
            "Chinese Crested dogs can get acne.",
            "February 1865 is the only month in recorded history not have a full moon.",
            "40% of all people who come to a party in your home snoop in your medicine cabinet",
            "It is illegal to hunt camels in the state of Arizona.",
            "Giant flying foxes that live in Indonesia have wingspans of nearly six feet.",
            "The first CD pressed in the US was Bruce Springsteen's “Born in the USA”.",
            "Eagles can live in captivity for up to 46 years.",
            "People photocopying their buttocks are the cause of 23% of all photocopier faults worldwide.",
            "When sharks take a bite, their eyes roll back and their teeth jut out.",
            "Your stomach produces a new layer of mucus every two weeks so that it doesn't digest itself.",
            "More people are allergic to cow's milk than any other food.",
            "The “spot” on the 7-Up logo comes from its inventor who had red eyes. He was an albino.",
            "The average human brain has about 100 billion nerve cells.",
            "There are more beetles than any other animal. In fact, one out of every four animals is a beetle.",
            "15 million blood cells are destroyed in the human body every second.",
            "A coward was originally a boy who took care of cows.",
            "The San Francisco Cable cars are the only mobile National Monuments",
            "Peanuts are one of the ingredients of dynamite.",
            "Only female mosquitoes bite.",
            "Devon is the only county in Great Britain to have two coasts.",
            "A group of finches is called a Charm.",
            "During the chariot scene in “Ben Hur,” a small red car can be seen in the distance.",
            "The angel falls in Venezuela are nearly 20 times taller than Niagara Falls.",
            "In the great fire of London in 1666 half of London was burnt down but only 6 people were injured.",
            "An enneahedron is solid with nine faces.",
            "Hedenophobic means fear of pleasure.",
            "For much of the way, the Lewis and Clark expedition was led by a woman, Sacagawea, a Shoshone Indian. That's where that saying came from'¦ Behind every successful man, there is a woman with a road map.",
            "There are no words in the dictionary that rhyme with orange, purple, silver and month.",
            "A man named Charles Osborne had the hiccups for 69 years!",
            "They NEVER said “Beam me up, Scotty” on Star Trek.",
            "The hammerthrow is illegal as a high school sport in all states except Rhode Island.",
            "Coca-Cola would be green if coloring weren't added to it.",
            "If you toss a penny 10,000 times it will not be heads 5000 times but more like 4950. The head picture weighs more, so it ends up on the bottom.",
            "Canadian researchers have found that Einstein's brain was 15% wider than normal.",
            "Humphrey Bogart NEVER said “Play it again, Sam” in Casablanca",
            "All Hebrew originating names that end with the letters el have something to do with God.",
            "A single sheeps fleece might well contain as many as 26 million fibres.",
            "Ham radio operators got the term ham coined from the expression ham-fisted operators a term used to describe early radio users who sent Morse code (i.e pounded their fists).",
            "Columbia University is the second largest landowner in New York City, after the Catholic Church.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "The bonobo monkeys use sex (and/or sexual favors) to placate members of their social group instead of grooming. They are one of the few species of animals (humans being another) that have sex out of season and for fun.",
            "Only one in two billion people will live to be 116 or older.",
            "It is illegal to eat oranges while bathing in California.",
            "Ethernet is a registered trademark of Xerox, Unix is a registered trademark of AT&T.",
            "French speaking residents of Belgium are called Walloons.",
            "The average shelf-life of a latex condom is about two years.",
            "An estimated 80% of animals on Earth have six legs.",
            "Because of the salt content of the Dead Sea, it is difficult to dive below its surface.",
            "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
            "All snow crystals are hexagonal.",
            "Bats always turn left when exiting a cave.",
            "If you yelled for 8 years, 7 months and six days, you would have produced enough sound energy to heat one cup of coffee.",
            "Average life span of a major league baseball: 7 pitches.",
            "Coca-Cola contained Coca (whose active ingredient is cocaine) from 1885 to 1903.",
            "The U.S. bought Alaska for 2 cents an acre from Russia.",
            "When you sneeze, all your bodily functions stop even your heart.",
            "There are over a million described species of insects. Some people estimate there are actually between 15 and 30 million species.",
            "The females of some moth species lack wings, all they can do to move is crawl.",
            "Scotland has more redheads than any other part of the world.",
            "Caterpillars have about four thousand muscles. Humans, by comparison, have only about six hundred.",
            "People eat insects - called “Entomophagy”(people eating bugs) - it has been practiced for centuries throughout Africa, Australia, Asia, the Middle East, and North, Central and South America. Why? Because many bugs are both protein-rich and good sources of vitamins, minerals and fats.",
            "The US has more personal computers than the next 7 countries combined.",
            "Go. is the shortest complete sentence in the English language.",
            "The first streetlights in America were installed in Philadelphia around 1757.",
            "Charlie Chaplin once won third prize in a Charlie Chaplin look-alike contest.",
            "Carolyn Shoemaker has discovered 32 comets and approximately 300 asteroids.",
            "Hippopotamuses do eighty percent of their vocalization under water.",
            "The odds of being born male are about 51.2%, according to census.",
            "Nepal is the only country that has a non-rectangular flag. It is also asymmetrical.",
            "Every year, Mexico City sinks about 10 inches.",
            "At the nearest point, Russia and America are less than 4 km apart.",
            "Flamingos can only eat with their heads upside down.",
            "A rainbow can only occur when the sun is 40 degrees or less above the horizon.",
            "It takes one fifteen-to-twenty-year-old tree to produce seven hundred paper grocery bags.",
            "Humans and dolphins are the only species that have sex for pleasure.",
            "Rhythm is the longest English word without a vowel.",
            "A group of frogs is called an army.",
            "A square mile of fertile earth has 32,000,000 earthworms in it.",
            "Impotence is legal grounds for divorce in 24 American states.",
            "A snake has no ears. But its tongue is extremely sensitive to sound vibrations. By flicking its tongue, a snake can pick up sound waves-so a snake `hears with his tongue'¦sort of!",
            "If you come from Manchester, you are a Mancunian.",
            "Dragonflies are capable of flying sixty miles per hour, making them one of the fastest insects. This is good since they are in a big hurry, as they only live about twenty-four hours.",
            "In Italy, it is illegal to make coffins out of anything except nutshells or wood.",
            "Elephants are the only mammals that cannot jump.",
            "Anne Boleyn, Queen Elizabeth I's mother, had six fingers on one hand.",
            "In England, the Speaker of the House is not allowed to speak.",
            "A group of rhinos are called a crash.",
            "Proportional to their size, cats have the largest eyes of all mammals.",
            "Cat's urine glows under a blacklight.",
            "A wind with a speed of 74 miles or more is designated a hurricane.",
            "Peter Falk, who played “Columbo,” has a glass eye.",
            "Right handed people live, on average, nine years longer than left-handed people",
            "Certain fireflies emit a light so penetrating that it can pass through flesh and wood.",
            "One quarter of the bones in your body, are in your feet!",
            "A forfeited game in baseball is recorded as a 9-0 score. In football it is recorded as a 1-0 score.",
            "A cubic mile of fog is made up of less than a gallon of water.",
            "Beetles taste like apples, wasps like pine nuts, and worms like fried bacon.",
            "At birth a panda is smaller than a mouse and weighs about four ounces.",
            "In 1990, Engineers digging a railway tunnel under the English Channel broke through the last dividing rock and joined Britain to mainland Europe for the first time since the Ice Age.",
            "Butte County, South Dakota is the geographical center of the U.S.",
            "Anteaters prefer termites to ants.",
            "A squirrel cannot contract or carry the rabies virus.",
            "A Czech man, Jan Honza Zampa, holds the record for drinking one liter of beer in 4.11 seconds.",
            "If you plant an apple seed, it is almost guaranteed to grow a tree of a different type of apple.",
            "Chinese Crested dogs can get acne.",
            "In English, four is the only digit that has the same number of letters as its value.",
            "Buckingham Palace in England has over six hundred rooms.",
            "In the average lifetime, a person will walk the equivalent of 5 times around the equator.",
            "There are about 24,000 species of butterflies. The moths are even more numerous: about 140,000 species of them were counted all over the world.",
            "Approximately 98% of software in China is pirated.",
            "No word in the English language rhymes with month, orange, silver, or purple.",
            "Some moths never eat anything as adults because they don't have mouths. They must live on the energy they stored as caterpillars.",
            "By raising your legs slowly and lying on your back, you cannot sink into quicksand.",
            "Georgia's state motto is “Wisdom, Justice and Moderation.”",
            "The Chuck E. Cheese franchise was created by Atari, a resteraunt combining robotic animals and arcade games with family meals. They name the franchise a Pizza Time Theater. Chuck E. Cheese was first opened in 1977.",
            "14% of Americans have skinny-dipped with a member of the opposite sex at least once.",
            "There is a city called Rome on every continent.",
            "Because of heavy traffic congestion, Julius Caesar banned all wheeled vehicles from Rome during daylight hours.",
            "If you bring a raccoon's head to the Henniker, New Hampshire town hall, you are entitled to receive $.10 from the town.",
            "By raising your legs slowly and lying on your back, you cannot sink into quicksand.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "The catfish has over 27000 taste buds (more than any other animal)",
            "When we think of Big Ben in London, we think of the clock. Actually, it's the bell.",
            "Right handed people live, on average, nine years longer than left handed people do.",
            "President John F Kennedy could read 4 newspapers in 20 minutes.",
            "Cyprus has a map on its flag.",
            "All of the clocks in the movie “Pulp Fiction” are stuck on 4:20.",
            "Negative emotions such as anxiety and depression can weaken your immune system.",
            "The toothbrush was invented in China in 1498.",
            "A snail can sleep for 3 years.",
            "It takes the insect-eating Venus Flytrap plant only half a second to shut its trap on its prey.",
            "Ghosts appear in 4 Shakespearian plays; Julius Caesar, Richard III, Hamlet and Macbeth.",
            "Mice, whales, elephants, giraffes and man all have seven neck vertebra.",
            "Iron nails cannot be used in aok because the acid in the wood corrodes them.",
            "Goethe couldn't stand the sound of barking dogs and could only write if he had an apple rotting in the drawer of his desk.",
            "Dominica, Mexico, Zambia, Kiribati, Fiji and Egypt all have birds on their flags.",
            "Bamboo (the world's tallest grass) can grow up to 90 cm in a day.",
            "All the dirt from the foundation to build the World Trade Center in NYC was dumped into the Hudson River to form the community now known as Battery City Park.",
            "A group of geese on the ground is called a gaggle, a group of geese in the air is a skein.",
            "A snail can sleep for three years.",
            "On average, 12 newborns will be given to the wrong parents daily.",
            "Ninety percent of New York City cabbies are recently arrived immigrants.",
            "Vatican City is the smallest country in the world, with a population of 1000 and just 108.7 acres.",
            "There are 45 miles of nerves in the skin of a human being.",
            "The average child recognizes over 200 company logos by the time he enters first grade.",
            "There are over 58 million dogs in the US",
            "Chameleons can move their eyes in two directions at the same time.",
            "Rubber bands last longer when refrigerated.",
            "Did you know you share a birthday with at least nine other million people in the world?",
            "About 55% of all movies are rated R.",
            "If you were to take a taxicab from New York City to Los Angeles, it would cost you $8,325.",
            "A poem written to celebrate a wedding is called a epithalamium.",
            "Australian soldiers used the song “We're Off to See the Wizard” as a marching song in WWII.",
            "Four men in the history of boxing have been knocked out in the first eleven seconds of the first round.",
            "Happy as a clam is from the expression happy as a clam at high tide. Clams are only harvested when the tide is out.",
            "All totalled, the sunlight that strikes Earth at any given moment weighs as much as an ocean liner.",
            "A snail takes 33 hours to crawl one mile.",
            "A rhinoceros' horn is made of compacted hair.",
            "A shrimp's heart is in its head.",
            "A skunk's smell can be detected by a human a mile away.",
            "The most sensitive cluster of nerves is at the base of the spine.",
            "The surface of the Earth is about 60% water and 10% ice.",
            "More people are afraid of spiders than death. Amazingly, few people are afraid of Champagne corks even though you are more likely to be killed by one than by a spider.",
            "”Judge Judy” has a $25,000,000 salary, while Supreme Court Justice Ginsberg has a $190,100 salary.",
            "The ZIP in “ZIP code” means Zoning Improvement Plan.",
            "Gary, Indiana is the murder capital of the U.S. - probably the world.",
            "Amphibious is based upon Greek words that mean living a double life and amphibians live in both land and water.",
            "In Miami, Florida, roosting vultures have taken to snatching poodles from rooftop patios.",
            "Coconuts kill about 150 people each year. That's more than sharks.",
            "According to the Gemological Institute of America, up until 1896, India was the only source for diamonds to the world.",
            "The shortest British monarch was Charles I, who was 4 feet 9 inches.",
            "A rat can last longer without water than a camel.",
            "40% of McDonald's profits come from the sales of Happy Meals.",
            "Christmas was once illegal in England.",
            "No word in the English language rhymes with “MONTH”.",
            "Women blink nearly twice as much as men.",
            "The average human eats 8 spiders in their lifetime at night.",
            "American Airlines saved $40,000 in 1987 by taking out an olive from First Class salads.",
            "The Australian $5 to $100 notes are made of plastic.",
            "Every person, including identical twins, has a unique eye & tongue print along with their finger print.",
            "Sweden has the least number of murders annually.",
            "The dot over the letter “i” is called a tittle.",
            "A manned rocket reaches the moon in less time than it took a stagecoach to travel the length of England.",
            "In England, in the 1880'˛s pants was considered a dirty word.",
            "In Paris, the McDonalds big `M' is the only one in the world that is white, rather than yellow, it was thought that yellow was too tacky.",
            "Earth is the only planet not named after a god.",
            "A group of goats is called a Trip.",
            "If the Earth was smooth, the ocean would cover the entire surface to a depth of 12,000 feet.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "The first CD pressed in the US was Bruce Springsteen's “Born in the USA.”",
            "Rubber bands last longer when refrigerated.",
            "Antarctica is the only continent on which no Lepidoptera have been found.",
            "Al Capone's business card said he was a used furniture dealer.",
            "“Ithyphallophobia” is a morbid fear of seeing, thinking about or having an erect penis.",
            "Americans on average eat 18 acres of pizza every day.",
            "In the Durango desert, in Mexico, there's a creepy spot called the Zone of Silence. You can't pick up clear TV or radio signals. And locals say fireballs sometimes appear in the sky.",
            "The world's youngest parents were 8 and 9 and lived in China in 1910.",
            "Sigmund Freud had a morbid fear of ferns.",
            "There are 336 dimples on a regulation US golf ball. In the UK its 330.",
            "Maine is the only state (in USA) whose name is just one syllable.",
            "When young, black sea basses are mostly female, but at the age of 5 years many switch sexes to male.",
            "In the 17th century, the value of pi was known to 35 decimal places. Today, to 1.2411 trillion.",
            "Women blink nearly twice as much as men.",
            "Each year in America there are about 300,000 deaths that can be attributed to obesity.",
            "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
            "Jimmy Carter was the first U.S. President to be born in a hospital.",
            "Facetious and abstemious contain all the vowels in the correct order, as does arsenious, meaning containing arsenic.",
            "160 cars can drive side by side on the Monumental Axis in Brazil, the world's widest road.",
            "Mongolia is the largest landlocked country.",
            "Maine is the only state (in USA) whose name is just one syllable.",
            "When young, black sea basses are mostly female, but at the age of 5 years many switch sexes to male.",
            "In the 17th century, the value of pi was known to 35 decimal places. Today, to 1.2411 trillion.",
            "Women blink nearly twice as much as men.",
            "Each year in America there are about 300,000 deaths that can be attributed to obesity.",
            "Women blink nearly twice as much as men.",
            "Some lions mate over 50 times a day.",
            "California has issued 6 drivers licenses to people named “Jesus Christ.”",
            "China's largest city is Shanghai.",
            "More people are afraid of open spaces (kenophobia) than of tight spaces (claustrophobia).",
            "A polar bears skin is black. Its fur is actually clear, but like snow it appears white.",
            "A Boeing 747'˛s wingspan is longer than the Wright brother's first flight.",
            "Butterflies can see red, green, and yellow.",
            "A “jiffy” is the scientific name for 1/100th of a second.",
            "The 57 on the Heinz ketchup bottle represents the number of pickle types the company once had.",
            "China has more English speakers than the United States.",
            "In the UK, there is no act of parliament making it illegal to commit murder. Murder is only illegal due to legal precedent.",
            "There are about 2 chickens for every human in the world.",
            "Of all the words in the English language, the word `set' has the most definitions!",
            "Sex is biochemically no different from eating large quantities of chocolate.",
            "Lee Harvey Oswald's cadaver tag sold at an auction for $6,600 in 1992.",
            "There is an average of 61,000 people airborne over the US at any given moment.",
            "According to Douglas Adams, a Salween is the faint taste of dishwashing liquid in a cup of fresh tea.",
            "A sizable oak tree, during the typical growing season, gives off 28,000 gallons of moisture.",
            "Dendrology is the study of trees.",
            "Louisiana's capital building is the tallest one of any U.S. state.",
            "You are more likely to be killed by a champagne cork than by a poisonous spider.",
            "Chevrolet tried marketing a Chevrolet Nova in Spanish speaking countries - it didn't sell well because NOVA means “doesn't go” in Spanish.",
            "A castrated male reindeer is called a bull.",
            "Alabama was the first state to recognize Christmas as an official holiday.",
            "A full moon always rises at sunset.",
            "A group of owls is called a parliament.",
            "There is a 1 in 4 chance that New York will have a white Christmas.",
            "The placement of a donkey's eyes in it's head enables it to see all four feet at all times!",
            "In 1386, a pig in France was executed by public hanging for the murder of a child",
            "Tasmania, Australia has the cleanest air in the inhabited world.",
            "Iguanas, koalas and Komodo dragons all have two penises.",
            "Butterflies and insects have their skeletons on the outside of their bodies, called the exoskeleton. This protects the insect and keeps water inside their bodies so they don't dry out.",
            "In York, it is perfectly legal to shoot a Scotsman with a bow and arrow (except on Sundays)",
            "John Lennon's first girlfriend was named Thelma Pickles.",
            "A blind chameleon still changes colors to match his environment.",
            "The Portuguese jellyfish tentacles have been known to grow a mile in length, catching anything in it's path by stinging it's prey.",
            "Icelanders consume more Coca-Cola per Capita than any other nation.",
            "A hedgehog's heart beats 300 times a minute on average.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            "Your brain generates 25 watts of power while you're awake. This amount of energy is enough to illuminate a lightbulb.",
            "In an analysis of 200000 ostriches over 80 years, not one tried to bury its head in the sand.",
            "The first toilet ever seen on television was on “Leave It to Beaver.”",
            "In ancient Greece “idiot” meant a private citizen or layman.",
            "In Jasmine, Saskatchewan, it is illegal for a cow to moo within 300 km of a private home.",
            "Because of a large orbital eccentricity, Pluto was closer to the sun than Neptune between January 1979 and March 1999.",
            "In Hartford, Connecticut, it is illegal for a husband to kiss his wife on Sundays.",
            "One in every 9000 people is an albino.",
            "Most household dust is made of dead skin cells.",
            "A cockroach will live nine days without its head before it starves to death.",
            "During his entire life, Vincent Van Gogh sold exactly one painting, “Red Vineyard at Arles”.",
            "Certain species of male butterflies produce scents that serve in attracting females during courtship.",
            "There are no clocks in Las Vegas gambling casinos.",
            "Male bees will try to attract sex partners with orchid fragrance.",
            "On a Canadian two-dollar bill, the American flag is flying over the Parliament Building.",
            "The crack of a whip is actually a tiny sonic boom, since the tip breaks the sound barrier.",
            "Jupiter is bigger than all the other planets in our solar system combined.",
            "Hot water is heavier than cold.",
            "Lawn darts are illegal in Canada.",
            "There are more psychoanalysts per capita in Buenos Aires than any other place in the world.",
            "There is a town in Newfoundland, Canada called Dildo.",
            " All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
            "In space, astronauts are unable to cry, because there is no gravity and the tears won't flow.",
            "Chewing gum while peeling onions will keep you from crying.",
            "There are more plastic flamingos in the U.S that there are real ones.",
            "The world record for spitting a watermelon seed is 65 feet 4 inches.",
            "In the Philippine jungle, the yo-yo was first used as a weapon.",
            "Dueling is legal in Paraguay as long as both parties are registered blood donors.",
            " Texas is also the only state that is allowed to fly its state flag at the same height as the U.S. flag.",
            "The three most recognized Western names in China are Jesus Christ, Richard Nixon, & Elvis Presley.",
            "It is illegal to eat oranges while bathing in California.",
            "If done perfectly, a rubix cube combination can be solved in 17 turns.",
            "The average American butt is 14.9 inches long.",
            "More bullets were fired in `Starship Troopers' than any other movie ever made.",
            "60% of electrocutions occur while talking on the telephone during a thunderstorm.",
            "Each month, there is at least one report of UFOs from each province of Canada.",
            "40,000 Americans are injured by toilets each year.",
            "You can be fined up to $1,000 for whistling on Sunday in Salt Lake City, Utah.",
            "It takes about 142.18 licks to reach the center of a Tootsie pop.",
            "The serial number of the first MAC ever produced was 2001.",
            "Between 25% and 33% of the population sneeze when exposed to light.",
            "The most common name in world is Mohammed.",
            "Mount Olympus Mons on Mars is three times the size of Mount Everest.",
            "Most toilets flush in E flat.",
            "2,000 pounds of space dust and other space debris fall on the Earth every day.",
            "The value of Pi will be officially “rounded down” to 3.14 from 3.14159265359 on December 31, 1999.",
            "The Great Wall of China is the only man-made structure visible from space.",
            "A piece of paper can be folded no more then 9 times.",
            "The amount of computer Memory required to run WordPerfect for Win95 is 8 times the amount needed aboard the space shuttle.",
            "The average North American will eat 35,000 cookies during their life span.",
            "Emus and kangaroos cannot walk backwards, and are on the Australian coat of arms for that reason.",
            "Cats have over one hundred vocal sounds, while dogs only have about ten.",
            "Blueberry Jelly Bellies were created especially for Ronald Reagan. ",
            "PEZ candy even comes in a Coffee flavor.",
            "The first song played on Armed Forces Radio during operation Desert Shield was “Rock the Casba” by the Clash. ",
            "The “save” icon on Microsoft Word shows a floppy disk with the shutter on backwards.",
            "The only nation whose name begins with an “A”, but doesn't end in an “A” is Afghanistan.",
            "The verb “cleave” is the only English word with two synonyms which are antonyms of each other: adhere and separate.",
            "The only 15-letter word that can be spelled without repeating a letter is uncopyrightable.",
            "The shape of plant collenchyma's cells and the shape of the bubbles in beer foam are the same - they are orthotetrachidecahedrons.",
            "The Black Widow spider eats her mate during or after sex.",
            "Napoleon's penis was sold to an American Urologist for $40,000.",
            "Eating the heart of a male Partridge was the cure for impotence in ancient Babylon.",
            "A bull can inseminate 300 cows from one single ejaculation.",
            "When a Hawaiian woman wears a flower over her left ear, it means that she is not available.",
            "In Aspen Colorado, you can have a maximum income of $104,000 and still receive government subsidized housing.",
            "Honking of car horns for a couple that just got married is an old superstition to insure great sex.",
            "Dr. Kellogg introduced Kellogg's Corn Flakes in hopes that it would reduce masturbation.",
            "The sperm of a mouse is actually longer than the sperm of an elephant.",
            "In medieval France, unfaithful wives were made to chase a chicken through town naked.",
            "The phrase “rule of thumb” is derived from an old English law, which stated that you couldn't beat your wife with anything wider than your thumb.",
            "The longest recorded flight of a chicken is thirteen seconds.",
            "The Eisenhower interstate system requires that one mile in every five must be straight in case of war or emergency, they could be used as airstrips.",
            "The name Jeep came from the abbreviation used in the army. G.P. for `General Purpose' vehicle.",
            "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
            "In the early 1940s, the FCC assigned television's Channel 1 to mobile services (like two-way radios in taxis) but did not re-number the other channel assignments.",
            "The San Francisco Cable cars are the only mobile National Monuments.",
            "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
            "“I am.” is the shortest complete sentence in the English language.",
            "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
            "Hong Kong holds the most Rolls Royce's per capita.",
            "Average number of days a West German goes without washing his underwear: 7",
            "Average number of people airborne over the US any given hour: 61,000.",
            "Intelligent people have more zinc and copper in their hair.",
            "Iceland consumes more Coca-Cola per capita than any other nation.",
            " Over 60% of all those who marry get divorced.",
            "400-quarter pounders can be made from 1 cow.",
            "A full-loaded supertanker traveling at normal speed takes at least 20 minutes to stop.",
            "Coca-Cola was originally green.",
            "Men can read smaller print than women; women can hear better.",
            "During a severe windstorm or rainstorm the Empire State Building sways several feet to either side.",
            "In the last 3,500 years, there have been approximately 230 years of peace throughout the civilized world.",
            " The Black Death reduced the population of Europe by one third in the period from 1347 to 1351.",
            "The average person spends about two years on the phone in a lifetime.",
            "Length of beard an average man would grow if he never shaved 27.5 feet",
            "Non-dairy creamer is flammable.",
            "The airplane Buddy Holly died in was the “American Pie.” (Thus the name of the Don McLean song.)",
            "Golf courses cover 4% of North America.",
            " The average person will accidentally eat just under a pound of insects every year.",
            "Until 1994, world maps and globes sold in Albania only had Albania on them.",
            "The average talker sprays about 300 microscopic saliva droplets per minute, about 2.5 droplets per word.",
            "The Earth experiences 50,000 Earth quakes per year and is hit by Lightning 100 times a second.",
            "Every year 11,000 Americans injure themselves while trying out bizarre sexual positions.",
            "If we had the same mortality rate now as in 1900, more than half the people in the world today would not be alive.",
            "On average, Americans eat 18 acres of pizza everyday.",
            "Tom Sawyer was the first novel written on a typewriter.",
            "If Texas were a country, its GNP would be the fifth largest of any country in the world.",
            "There are 1 million ants for every human in the world.",
            "The `Golden Arches' of fast food chain McDonalds is more recognized worldwide than the religious cross of Christianity.",
            "Former basketball superstar Michael Jordan is the most recognized face in the world, more than the pope himself.",
            "Average life span of a major league baseball: 7 pitches.",
            " The first CD pressed in the US was Bruce Springsteen's `Born in the USA'",
            "The thumbnail grows the slowest, the middle nail the fastest, nearly 4 times faster than toenails.",
            "The Human eyes never grow, but nose and ears never stop growing.",
            "The 57 on Heinz ketchup bottles represents the number of varieties of pickles the company once had.",
            "If you go blind in one eye you only lose about one fifth of your vision but all your sense of depth.",
            " Women blink nearly twice as much as men.",
            "The strongest muscle (Relative to size) in the body is the tongue.",
            " A Boeing 747'˛s wingspan is longer than the Wright brother's first flight.",
            "American Airlines saved $40,000 in 1987 by eliminating one olive from each salad served in first-class. ",
            "1 in 8 Americans has worked at a McDonalds restaurant.",
            "70% of all boats sold are used for fishing.",
            "A pregnant goldfish is called a twit.",
            " The shortest war in history was between Zanzibar and England in 1896. Zanzibar surrendered after 38 minutes. ",
            "You were born with 300 bones, but by the time you are an adult you will only have 206.",
            "The human heart creates enough pressure to squirt blood 30ft.",
            "One third of all cancers are sun related.",
            "It has been estimated that humans use only 10% of their brain.",
            "Most Egyptians died by the time they were 30 about 300 years ago,",
            " 1 in every 4 Americans has appeared someway or another on television.",
            "A literal translation of a standard traffic sign in China: “Give large space to the festive dog that makes sport in the roadway.”",
            " You burn more calories sleeping than you do watching TV.",
            "Larry Lewis ran the 100-yard dash in 17.8 seconds in 1969, thereby setting a new world's record for runners in the 100-years-or-older class. He was 101.",
            "In a lifetime the average human produces enough quarts of spit to fill 2 swimming pools.",
            "Barbie's measurements, if she were life-size, would be 39-29-33.",
            "In 1778, fashionable women of Paris never went out in blustery weather without a lightning rod attached to their hats.",
            "Sex burns 360 calories per hour.",
            "A raisin dropped in a glass of fresh champagne will bounce up and down continually from the bottom of the glass to the top.",
            "Celery has negative calories! It takes more calories to eat a piece of celery than the celery has in it.",
            " The pop you hear when you crack your knuckles is actually a bubble of gas burning.",
            " In eighteenth-century English gambling dens, there was an employee whose only job was to swallow the dice if there was a police raid.",
            "There are no clocks in Las Vegas gambling casinos.",
            " The first product to have a bar code was Wrigley's gum.",
            "Annual growth of WWW traffic is 314,000%",
            "%60 of all people using the Internet, use it for pornography.",
            "One-fourth of the world's population lives on less than $200 a year.  Ninety million people survive on less than $75 a year.",
            "Butterflies taste with their hind feet.",
            "Only female mosquito's' bite and most are attracted to the color blue twice as much as to any other color.",
            "If one places a tiny amount of liquor on a scorpion, it will instantly go mad and sting itself to death.",
            "It is illegal to hunt camels in the state of Arizona.",
            "It has NEVER rained in Calama, a town in the Atacama Desert of Chile.",
            "The plastic things on the end of shoelaces are called aglets.",
            "Daylight Saving Time is not observed in most of the state of Arizona and parts of Indiana.",
            "Ants closely resemble human manners:  When they wake, they stretch & appear to yawn in a human manner before taking up the tasks of the day.",
            "Bees have 5 eyes. There are 3 small eyes on the top of a bee's head and 2 larger ones in front.",
            "Ninety percent of all species that have become extinct have been birds.",
            "There is approximately one chicken for every human being in the world.",
            " Most collect calls are made on father's day.",
            "Each of us generates about 3.5 pounds of rubbish a day, most of it paper.",
            "Women manage the money and pay the bills in  75% of all Americans households.",
            "Right-handed people live, on average; nine years longer than left handed people.",
            "Ten percent of the Russian government's income comes from the sale of vodka.",
            "In the United States, a pound of potato chips costs two hundred times more than a pound of potatoes.  ",
            "A giraffe can go without water longer than a camel.",
            " Nearly 80% of all animals on earth have six legs.",
            "The average person spends 6 months of their life sitting at red lights.",
            "More Monopoly money is printed in a year, than real money throughout the world.",
            "Caesar salad has nothing to do with any of the Caesars. It was first concocted in a bar in Tijuana, Mexico, in the 1920'˛s.",
            "One quarter of the bones in your body are in your feet.",
            "Seattle's Fremont Bridge rises up and down more than any drawbridge in the world.",
            "The very first bomb dropped by the Allies on Berlin during World War II Killed the only elephant in the Berlin Zoo.",
            "More people are killed annually by donkeys than airplane crashes.",
            "A `jiffy' is a unit of time for 1/100th of a second.",
            "A whale's penis is called a dork.",
            "Because of the rotation of the earth, an object can be thrown farther if it is thrown west.",
            "Welcome to WordPress. This is your first post. Edit or delete it, then start blogging!",
            "Reindeer like to eat bananas.",
            "No word in the English language rhymes with month, orange, silver and purple.",
            "The word “samba” means “to rub navels together.”",
            "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
            "The electric chair was invented by a dentist.",
            "Your stomach has to produce a new layer of mucus every 2 weeks otherwise it will digest itself.",
            "The citrus soda 7-UP was created in 1929; '7'˛ was selected after the original 7-ounce containers and `UP' for the direction of the bubbles.",
            "A pig's orgasm lasts for 30 minutes.",
            "`Stewardesses' is the longest word that is typed with only the left hand.",
            "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
            "Most American car horns honk in the key of F.",
            "The name Wendy was made up for the book “Peter Pan.”",
            "Barbie's full name is Barbara Millicent Roberts.",
            "Every time you lick a stamp, you consume 1/10 of a calorie.",
            "The average person falls asleep in seven minutes.",
            "The world's termites outweigh the world's humans 10 to 1.",
            "Pound for pound, hamburgers cost more than new cars.",
            "The 3 most valuable brand names on earth: Marlboro, Coca-Cola, and Budweiser, in that order.",
            "When Heinz ketchup leaves the bottle, it travels at a rate of 25 miles per year.",
            "Elephants can't jump.  Every other mammal can.",
            "The name Wendy was made up for the book “Peter Pan.”",
            "In Cleveland, Ohio, it's illegal to catch mice without a hunting license.",
            "It takes 3,000 cows to supply the NFL with enough leather for a year's supply of footballs.",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "There are an average of 178 sesame seeds on a McDonald's Big Mac bun.",
            "111,111,111 x 111,111,111 = 12,345,678,987,654,321",
            "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
            "The phrase “rule of thumb” is derived from an old English law which stated that you couldn't beat your wife with anything wider than your thumb.",
            "The name Jeep came from the abbreviation used in the army for the “General Purpose” vehicle, G.P.",
            "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
            "A cat's jaw cannot move sideways.",
            "The sentence, “The quick brown fox jumps over the lazy dog,” uses every letter in the alphabet.",
            "Average life span of a major league baseball: 7 pitches.",
            "The airplane Buddy Holly died in was the “American Pie” (Thus the name of the Don McLean song).",
            "When opossums are playing `possum, they are not “playing.”  They actually pass out from sheer terror.",
            "The giant red star Betelgeuse has a diameter larger than that of the Earth's orbit around the sun.",
            "The longest place name still in use is: Taumatawhakatangihangaoauauotam-eteaturipukakapikimaungahoronukupokai-whenu a kitanatahu - a New Zealand hill.",
            "Only 1 in 2,000,000,000 will live to be 116 or older.",
            "When you tie a noose, the rope is wrapped twelve times around because it's the same length as a persons head.",
            "Hummingbirds are the only animal that can fly backwards.",
            "Chinese Crested dogs can get acne.",
            "Hydrogen gas is the least dense substance in the world, at 0.08988g/cc.  Hydrogen solid is the most dense substance in the world, at 70.6g/cc.",
            "Each year there is one ton of cement poured for each man woman and child in the world.",
            "The house fly hums in the middle octave key of F.",
            "The only capital letter in the Roman alphabet with exactly one end point is P.",
            "The most common name in the world is Mohammed.",
            "Michael Jordan makes more money from NIKE annually than all of the Nike factory workers in Malaysia combined.",
            "The volume of the Earth's moon is the same as the volume of the Pacific Ocean.",
            "Cephalacaudal recapitulation is the reason our extremities develop Faster than the rest of us.",
            "The slogan on New Hampshire license plates is “Live Free or Die.”  These license plates are manufactured by prisoners in the state prison in Concord.",
            "The “dot” over the letter “i” is called a tittle.",
            "Table tennis balls have been known to travel off the paddle at speeds up to 160 km/hr.",
            "Pepsi originally contained pepsin, thus the name.",
            "The original story from “Tales of 1001 Arabian Nights” begins, “Aladdin was a little Chinese boy.”",
            "Nutmeg is extremely poisonous if injected intravenously.",
            "The average person falls asleep in seven minutes.",
            "There are 336 dimples on a regulation golf ball.",
            "`Stewardesses' is the longest word that is typed with only the left hand.",
            "The “pound” key on your keyboard (#) is called an octotroph.",
            "The only domestic animal not mentioned in the Bible is the cat.",
            "The male gypsy moth can “smell” the virgin female gypsy moth from 1.8 miles away (pretty good trick).",
            "In England, the Speaker of the House is not allowed to speak.",
            "The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
            "Mr. Rogers is an ordained minister.",
            "John Lennon's first girlfriend was named Thelma Pickles.",
            "A goldfish has a memory span of three seconds.",
            "A dime has 118 ridges around the edge.",
            "It's impossible to sneeze with your eyes open.",
            "The giant squid has the largest eyes in the world.",
            "Who's that playing the piano on the “Mad About You” theme?  Paul Reiser himself.",
            "Al Capone's business card said he was a used furniture dealer.",
            "The only real person to be a Pez head was Betsy Ross.",
            "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state's third largest city.",
            "The characters Bert and Ernie on Sesame Street were named after Bert the cop and Ernie the taxi driver in Frank Capra's “Its A Wonderful Life”",
            "A dragonfly has a lifespan of 24 hours.",
            "There are only four words in the English language which end in “dous”: tremendous, horrendous, stupendous, and hazardous.",
            "A cat has 32 muscles in each ear.",
            "An ostrich's eye is bigger than it's brain.",
            "Tigers have striped skin, not just striped fur.",
            "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
            "“Dreamt” is the only English word that ends in the letters “mt”.",
            "All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
            "Almonds are members of the peach family.",
            "Winston Churchill was born in a ladies' room during a dance.",
            "Maine is the only state whose name is just one syllable.",
            "There are more chickens than people in the world (at least before that chicken-flu thing).",
            "Two-thirds of the world's eggplant is grown in New Jersey.",
            "The longest one-syllable word in the English language is “screeched.”",
            "All of the clocks in the movie Pulp Fiction are stuck on 4:20.",
            "No word in the English language rhymes with month, orange, silver or purple.",
            "Peanuts are one of the ingredients of dynamite.",
            "The national anthem of Greece has 158 verses.  No one in Greece has memorized all 158 verses.",
            "There are 293 ways to make change for a dollar.",
            "The average secretary's left hand does 56% of the typing.",
            "A shark is the only fish that can blink with both eyes.",
            "An ostrich's eye is bigger than its brain.",
            "Starfish have no brains.",
            "Polar bears are left-handed.",
            "Humans and dolphins are the only species that have sex for pleasure.",
            "Rubber bands last longer when refrigerated.",
            "The catfish has over 27,000 taste buds.",
            "Some lions mate over 50 times a day.",
            "Butterflies taste with their feet.",
            "The strongest muscle in the body is the tongue.",
            "A cat's urine glows under a black light.",
            "A pig's orgasm lasts 30 minutes.",
            "A cockroach will live nine days without its head before it starves to death!",
            "Banging your head against a wall uses 150 calories a hour",
            "The male praying mantis cannot copulate while its head is attached to its body. The female initiates sex by ripping the male's head off.",
            "The flea can jump 350 times its body length. It's like a human jumping the length of a football field.",
            "The average person laughs 10 times a day!",
            "An ostrich's eye is bigger than its brain",
            "If you yelled for 8 years, 7 months and 6 days you would have produced enough sound energy to heat one cup of coffee.",
            "If you farted consistently for 6 years and 9 months, enough gas is produced to create the energy of an atomic bomb.",
            "The human heart! creates enough pressure when it pumps out to the body to squirt blood 30 feet.",
            "Queen Elizabeth I regarded herself as a paragon of cleanliness. She declared that she bathed once every three months, whether she needed it or not",
            "Slugs have 4 noses.",
            "Owls are the only birds who can see the colour blue.",
            "A man named Charles Osborne had the hiccups for 69 years!",
            "A giraffe can clean its ears with its 21-inch tongue!",
            "Some worms will eat themselves if they can't find any food!",
            "Dolphins sleep with one eye open!",
            "It is impossible to sneeze with your eyes open",
            "The worlds oldest piece of chewing gum is 9000 years old!",
            "The longest recorded flight of a chicken is 13 seconds",
            "The placement of a donkey's eyes in its' heads enables it to see all four feet at all times!",
            "The six official languages of the United Nations are: English, French, Arabic, Chinese, Russian and Spanish.",
            "Earth is the only planet not named after a god.",
            "It's against the law to burp, or sneeze in a church in Nebraska, USA.",
            "You're born with 300 bones, but by the time you become an adult, you only have 206.",
            "On average a hedgehog's heart beats 300 times a minute.",
            "More people are killed each year from bees than from snakes.",
            "The average lead pencil will draw a line 35 miles long or write approximately 50,000 English words.",
            "More people are allergic to cow's milk than any other food.",
            "Camels have three eyelids to protect themselves from blowing sand.",
            "Women blink nearly twice as much as men.",
            "Adolf Hitler was a vegetarian, and had only ONE testicle.",
            "Honey is the only food that does not spoil. Honey found in the tombs of Egyptian pharaohs has been tasted by archaeologists and found edible.",
            "Months that begin on a Sunday will always have a “Friday the 13th.”",
            "Coca-Cola would be green if colouring weren't added to it.",
            "Like fingerprints, everyone's tongue print is different!",
            "The first known transfusion of blood was performed as early as 1667, when Jean-Baptiste, transfused two pints of blood from a sheep to a young man",
            "Fingernails grow nearly 4 times faster than toenails!",
            "Most dust particles in your house are made from dead skin!",
            "The present population of 5 billion plus people of the world is predicted to become 15 billion by 2080.",
            "The skeleton of Jeremy Bentham is present at all important meetings of the University of London",
            "Right handed people live, on average, nine years longer than left-handed people",
            "Your ribs move about 5 million times a year, everytime you breathe!",
            "The elephant is the only mammal that can't jump!",
            "One quarter of the bones in your body, are in your feet!",
            "You can't kill yourself by holding your breath",
            "There is a city called Rome on every continent.",
            "It used to be against the law to have a pet dog in Iceland.",
            "Your heart beats over 100,000 times a day.",
            "Horatio Nelson, one of England's most illustrious admirals was throughout his life, never able to find a cure for his sea-sickness.",
            "“Almost” is the longest word in the English language with all the letters in alphabetical order.",
            "“Rhythm” is the longest English word without a vowel.",
            "In 1386, a pig in France was executed by public hanging for the murder of a child",
            "A cockroach can live several weeks with its head cut off.",
            "Human thigh bones are stronger than concrete.",
            "Astronauts are not allowed to eat beans before they go into space because passing wind in a space suit damages them.",
            "The word “queue” is the only word in the English language that is still pronounced the same way when the last four letters are removed.",
            "Beetles taste like apples, wasps like pine nuts, and worms like fried bacon.",
            "Of all the words in the English language, the word 'set' has the most definitions!",
            "What is called a “French kiss” in the English speaking world is known as an “English kiss” in France.",
            "A tiny amount of liquor on a scorpion will make it instantly go mad and sting itself to death.",
            "The mask used by Michael Myers in the original “Halloween” was a Captain Kirk mask painted white.",
            "Chewing gum while peeling onions will keep you from crying!",
            "The glue on Israeli postage stamps is certified kosher.",
            "Guinness Book of Records holds the record for being the book most often stolen from Public Libraries.",
            "Because metal was scarce, the Oscars given out during World War II were made of wood.",
            "There are no clocks in Las Vegas gambling casinos.",
            "The name Wendy was made up for the book Peter Pan, there was never a recorded Wendy before!",
            "There are no words in the dictionary that rhyme with: orange, purple, and silver!",
            "Leonardo Da Vinci invented scissors.",
            "Orcas (killer whales) kill sharks by torpedoing up into the shark's stomach from underneath, causing the shark to explode.",
            "Most lipstick contains fish scales.",
            "Donald Duck comics were banned from Finland because he doesn't wear any pants.",
            "Ketchup was sold in the 1830s as medicine.",
            "Leonardo da Vinci could write with one hand and draw with the other at the same time.",
            "Every person has a unique tongue print as well as fingerprints.",
            "315 entries in Webster's 1996 Dictionary were misspelled.",
            "On average, 12 newborns will be given to the wrong parents daily.",
            "During the chariot scene in `Ben Hur' a small red car can be seen in the distance.",
            "Warren Beatty and Shirley MacLaine are brother and sister.",
            "The 57 on Heinz ketchup bottle represents the varieties of pickle the company once had.",
            "Your stomach produces a new layer of mucus every two weeks - otherwise it will digest itself.",
            "The Declaration of Independence was written on hemp paper.",
            "A raisin dropped in a glass of fresh champagne will bounce up and down continuously from the bottom of the glass to the top.",
            "Susan Lucci is the daughter of Phyllis Diller.",
            "Jellyfish like salt water. A rainy season often reduces the jellyfish population by putting more fresh water into normally salty waters where they live.",
            "The female lion does ninety percent of the hunting.",
            "A group of twelve or more cows is called a flink.",
            "You can tell the sex of a horse by its teeth. Most males have 40, females have 36.",
            "Money isn't made out of paper; it's made out of cotton.",
            "North American oysters do not make pearls of any value.",
            "Human birth control pills work on gorillas.",
            "Gorillas sleep as much as fourteen hours per day.",
            "A biological reserve has been made for golden toads because they are so rare.",
            "There are more than fifty different kinds of kangaroos.",
            "Deer can't eat hay.",
            "Gopher snakes in Arizona are not poisonous, but when frightened they may hiss and shake their tails like rattlesnakes.",
            "On average, dogs have better eyesight than humans, although not as colorful.",
            "The duckbill platypus can store as many as six hundred worms in the pouches of its cheeks.",
            "The lifespan of a squirrel is about nine years.",
            "Guinea pigs and rabbits can't sweat.",
            "According to the Wall Street Journal, the cockfighting market is huge: The Philippines has five million roosters used for exactly that.",
            "The porpoise is second to man as the most intelligent animal on the planet.",
            "Young beavers stay with their parents for the first two years of their lives before going out on their own.",
            "Skunks can accurately spray their smelly fluid as far as ten feet.",
            "Western Electric successfully brought sound to motion pictures and introduced systems of mobile communications which culminated in the cellular telephone.",
            "On December 23, 1947, Bell Telephone Laboratories in Murray Hill, N.J., held a secret demonstration of the transistor which marked the foundation of modern electronics.",
            "Ostriches are often not taken seriously. They can run faster than horses, and the males can roar like lions.",
            "Seals used for their fur get extremely sick when taken aboard ships.",
            "Sloths take two weeks to digest their food.",
            "On average, half of all false teeth have some form of radioactivity.",
            "Only one satellite has been ever been destroyed by a meteor: the European Space Agency's Olympus in 1993.",
            "A ball of glass will bounce higher than a ball of rubber. A ball of solid steel will bounce higher than one made entirely of glass.",
            "A chip of silicon a quarter-inch square has the capacity of the original 1949 ENIAC computer, which occupied a city block.",
            "At a jet plane's speed of 1,000 km (620mi) per hour, the length of the plane becomes one atom shorter than its original length.",
            "Hot water is heavier than cold.",
            "Plutonium - first weighed on August 20th, 1942, by University of Chicago scientists Glenn Seaborg and his colleagues - was the first man-made element.",
            "If you went out into space, you would explode before you suffocated because there's no air pressure.",
            "The radioactive substance, Americanium - 241 is used in many smoke detectors.",
            "Sound travels 15 times faster through steel than through the air.",
            "Outside the USA, Ireland is the largest software producing country in the world.",
            "The first fossilized specimen of Australopithecus afarenisis was named Lucy after the paleontologists' favorite song “Lucy in the Sky with Diamonds,” by the Beatles.",
            "Figlet, an ASCII font converter program, stands for Frank, Ian and Glenn's LETters.",
            "Every human spent about half an hour as a single cell.",
            "Every year about 98% of atoms in your body are replaced.",
            "If the amount of water in your body is reduced by just 1%, you'll feel thirsty.",
            "If it's reduced by 10%, you'll die.",
            "Ethernet is a registered trademark of Xerox, Unix is a registered trademark of AT&T.",
            "Bill Gates' first business was Traff-O-Data, a company that created machines which recorded the number of cars passing a given point on a road.",
            "Uranus' orbital axis is tilted at 90 degrees.",
            "Most lipstick contains fish scales.",
            "Like fingerprints, everyone's tongue print is different.",
            "Over 75% of people who read this will try to lick their elbow.",
            "A crocodile can't move its tongue and cannot chew. Its digestive juices are so strong that it can digest a steel nail.",
            "A person can live without food for about a month, but only about a week without water.",
            "The cigarette lighter was invented before the match.",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "A duck's quack doesn't echo, and no one knows why.",
            "23% of all photocopier faults worldwide are caused by people sitting on them and photocopying their butts.",
            "In the course of an average lifetime you will, while sleeping, eat 70 assorted insects and 10 spiders.",
            "If you try to suppress a sneeze, you can rupture a blood vessel in your head or neck and die.",
            "If you keep your eyes open by force when you sneeze, you might pop an eyeball out.",
            "Rats multiply so quickly that in 18 months, two rats could have over a million descendants.",
            "Wearing headphones for just an hour will increase the bacteria in your ear by 700 times.",
            "In every episode of Seinfeld there is a Superman somewhere.",
            "It is physically impossible for pigs to look up into the sky.",
            "A pregnant goldfish is called a twit.",
            "More than 50% of the people in the world have never made or received a telephone call.",
            "Rats and horses can't vomit.",
            "If you sneeze too hard, you can fracture a rib.",
            "Donald Duck comics were banned from Finland because he doesn't wear trousers.",
            "Ketchup was sold in the 1830s as medicine",
            "A crocodile can't stick it's tongue out.",
            "A shrimp's heart is in it's head.",
            "People say “Bless you” when you sneeze because when you sneeze,your heart stops for a mili-second.",
            "The phrase “rule of thumb” is derived from an old English law which stated that you couldn't beat your wife with anything wider than your thumb.",
            "The cruise liner Queen Elizabeth II, moves only six inches for each gallon of fuel that it burns.",
            "A Saudi Arabian woman can get a divorce if her husband doesn't give her coffee.",
            "The dot over the letter `i' is called a tittle.",
            "Most lipstick contains fish scales.",
            "The city with the most Roll Royces per capita: Hong Kong",
            "Percentage of Africa that is wilderness: 28% Percentage of North America that is wilderness: 38%",
            "Barbie's measurements if she were life size: 39-23-33",
            "Cost of raising a medium-sized dog to the age of 11: ÂŁ4000",
            "The name Jeep came from the abbreviation used in the army for the “General Purpose” vehicle, G.P.",
            "Debra Winger was the voice of E.T.",
            "During the chariot scene in `Ben Hur' a small red car can be seen in the distance.",
            "The first couple to be shown in bed together on prime time television were Fred and Wilma Flintstone.",
            "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
            "Every day more money is printed for monopoly than the US Treasury.",
            "Months that begin on a Sunday will always have a “Friday the 13th.”",
            "First novel ever written on a typewriter: Tom Sawyer",
            "The mask used by Michael Myers in the original film “Halloween” was actually a Captain Kirk mask painted white.",
            "James Doohan, who played Lt. Commander Montgomery Scott on Star Trek, was missing the entire middle finger of his right hand.",
            "All of the clocks in the movie “Pulp Fiction” are stuck on 4:20.",
            "Leonardo da Vinci could write with one hand and draw with the other at the same time.",
            "Sherlock Holmes never said “Elementary, my dear Watson”.",
            "In “Casablanca”, Humphrey Bogart never said “Play it again, Sam”.",
            "In the TV series I Love Lucy, Ricki Ricardo never actually said “Lucy you have some `splaining to do”",
            "A `jiffy' is an actual unit of time: 1/100th of a second.",
            "The most common name in the world is Mohammed.",
            "Intelligent people have more zinc and copper in their hair.",
            "The world's youngest parents were 8 and 9 and lived in China in 1910.",
            "The youngest Pope was 11 years old.",
            "Einstein couldn't speak fluently when he was nine. His parents thought he might be retarded.",
            "Babies are born without kneecaps. They don't appear until the child reaches 2-6 years of age.",
            "The 3 most valuable brand names on earth: Marlboro, Coca-Cola, and Budweiser, in that order.",
            "Coca Cola was originally green.",
            "40% of McDonald's profits come from the sales of Happy Meals.",
            "Every person has a unique tongue print.",
            "Certain frogs can be frozen solid, then thawed, and survive.",
            "Cat's urine glows under a black light.",
            "A shark can detect one part of blood in 100 million parts of water.",
            "A rat can last longer without water than a camel.",
            "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
            "The word “samba” means “to rub navels together.”",
            "Mel Blanc (the voice of Bugs Bunny) was allergic to carrots.",
            "The electric chair was invented by a dentist.",
            "The very first bomb dropped by the Allies on Berlin during World War II Killed the only elephant in the Berlin Zoo.",
            "More people are killed annually by donkeys than airplane crashes.",
            "A pig's orgasm lasts for 30 minutes.",
            "`Stewardesses' is the longest word that is typed with only the left hand.",
            "To escape the grip of a crocodile's jaws, push your thumbs into its eyeballs - it will let you go instantly.",
            "Reindeer like to eat bananas.",
            "No word in the English language rhymes with month, orange, silver and purple.",
            "The name Wendy was made up for the book “Peter Pan.”",
            "Barbie's full name is Barbara Millicent Roberts.",
            "Every time you lick a stamp, you consume 1/10 of a calorie.",
            "Your stomach has to produce a new layer of mucus every 2 weeks otherwise it will digest itself.",
            "The citrus soda 7-UP was created in 1929; '7'˛ was selected after the original 7-ounce containers and `UP' for the direction of the bubbles.",
            "The world's termites outweigh the world's humans 10 to 1.",
            "Pound for pound, hamburgers cost more than new cars.",
            "The 3 most valuable brand names on earth: Marlboro, Coca-Cola, and Budweiser, in that order.",
            "Elephants can't jump. Every other mammal can.",
            "Most American car horns honk in the key of F.",
            "The cruise liner, Queen Elizabeth II, moves only six inches for each gallon of diesel that it burns.",
            "The name Wendy was made up for the book “Peter Pan.”",
            "In Cleveland, Ohio, it's illegal to catch mice without a hunting license.",
            "It takes 3,000 cows to supply the NFL with enough leather for a year's supply of footballs.",
            "Thirty-five percent of the people who use personal ads for dating are already married.",
            "Average life span of a major league baseball: 7 pitches.",
            "The airplane Buddy Holly died in was the “American Pie” (Thus the name of the Don McLean song).",
            "When opossums are playing `possum, they are not “playing.”  They actually pass out from sheer terror.",
            "Hershey's Kisses are called that because the machine that makes them looks like it's kissing the conveyor belt.",
            "The name Jeep came from the abbreviation used in the army for the “General Purpose” vehicle, G.P.",
            "Only 1 in 2,000,000,000 will live to be 116 or older.",
            "When you tie a noose, the rope is wrapped twelve times around because it's the same length as a persons head.",
            "Hummingbirds are the only animal that can fly backwards.",
            "A cat's jaw cannot move sideways.",
            "The sentence, “The quick brown fox jumps over the lazy dog,” uses every letter in the alphabet.",
            "Each year there is one ton of cement poured for each man woman and child in the world.",
            "The house fly hums in the middle octave key of F.",
            "The only capital letter in the Roman alphabet with exactly one end point is P.",
            "The giant red star Betelgeuse has a diameter larger than that of the Earth's orbit around the sun.",
            "The longest place name still in use is: Taumatawhakatangihangaoauauotam-eteaturipukakapikimaungahoronukupokai-whenu a kitanatahu - a New Zealand hill.",
            "The volume of the Earth's moon is the same as the volume of the Pacific Ocean.",
            "Cephalacaudal recapitulation is the reason our extremities develop Faster than the rest of us.",
            "The slogan on New Hampshire license plates is “Live Free or Die.”  These license plates are manufactured by prisoners in the state prison in Concord.",
            "Chinese Crested dogs can get acne.",
            "Hydrogen gas is the least dense substance in the world, at 0.08988g/cc.  Hydrogen solid is the most dense substance in the world, at 70.6g/cc.",
            "Pepsi originally contained pepsin, thus the name.",
            "The original story from “Tales of 1001 Arabian Nights” begins, “Aladdin was a little Chinese boy.”",
            "Nutmeg is extremely poisonous if injected intravenously.",
            "The most common name in the world is Mohammed.",
            "Michael Jordan makes more money from NIKE annually than all of the Nike factory workers in Malaysia combined.",
            "`Stewardesses' is the longest word that is typed with only the left hand.",
            "The “pound” key on your keyboard (#) is called an octotroph.",
            "The only domestic animal not mentioned in the Bible is the cat.",
            "The “dot” over the letter “i” is called a tittle.",
            "Table tennis balls have been known to travel off the paddle at speeds up to 160 km/hr.",
            "The microwave was invented after a researcher walked by a radar tube and a chocolate bar melted in his pocket.",
            "Mr. Rogers is an ordained minister.",
            "John Lennon's first girlfriend was named Thelma Pickles.",
            "The average person falls asleep in seven minutes.",
            "There are 336 dimples on a regulation golf ball.",
            "It's impossible to sneeze with your eyes open.",
            "The giant squid has the largest eyes in the world.",
            "Who's that playing the piano on the “Mad About You” theme?  Paul Reiser himself.",
            "The male gypsy moth can “smell” the virgin female gypsy moth from 1.8 miles away (pretty good trick).",
            "In England, the Speaker of the House is not allowed to speak.",
            "The only real person to be a Pez head was Betsy Ross.",
            "When the University of Nebraska Cornhuskers play football at home, the stadium becomes the state's third largest city.",
            "A dragonfly has a lifespan of 24 hours.",
            "A goldfish has a memory span of three seconds.",
            "A dime has 118 ridges around the edge.",
            "A cat has 32 muscles in each ear.",
            "An ostrich's eye is bigger than it's brain.",
            "Tigers have striped skin, not just striped fur.",
            "In most advertisements, including newspapers, the time displayed on a watch is 10:10.",
            "Al Capone's business card said he was a used furniture dealer.",
            "Angry birds has been bought 700 MILLION times and has become an international brand.",
            "David Cameron, Paul Gascoigne, Kylie Minogue, Conan O'Brien and Jon Hamm, Mad Men's Don Draper are great fans.",
            "An Angry Birds Land is open at a theme park in Tampere, Finland.",
            "More than ten million cuddly toys have been sold and you can also buy notebooks, lunchboxes, bed spreads and clothes.",
            "A team of four people made angry birds in eight months.",
            "All 50 states are listed across the top of the Lincoln Memorial on the back of the $5 bill.",
            "Almonds are members of the peach family.",
            "Winston Churchill was born in a ladies' room during a dance.",
            "Maine is the only state whose name is just one syllable.",
            "There are only four words in the English language which end in “dous”: tremendous, horrendous, stupendous, and hazardous.",
            "Two-thirds of the world's eggplant is grown in New Jersey.",
            "The longest one-syllable word in the English language is “screeched.”",
            "All of the clocks in the movie Pulp Fiction are stuck on 4:20.",
            "No word in the English language rhymes with month, orange, silver or purple.",
            "“Dreamt” is the only English word that ends in the letters “mt”.",
            "The national anthem of Greece has 158 verses.  No one in Greece has memorized all 158 verses.",
            "There are 293 ways to make change for a dollar.",
            "The average secretary's left hand does 56% of the typing.",
            "A shark is the only fish that can blink with both eyes.",
            "There are more chickens than people in the world (at least before that chicken-flu thing).",
            "An ostrich's eye is bigger than its brain.",
            "Starfish have no brains.",
            "Polar bears are left-handed.",
            "Humans and dolphins are the only species that have sex for pleasure.",
            "Peanuts are one of the ingredients of dynamite.",
            "A cat's jaw cannot move sideways.",
            "A Flemish artist is responsible for the world's smallest paintings in history. It is a picture of a miller and his mill, and it was painted onto a grain of corn.",
            "Golden toads are so rare that a biological reserve has been specifically created for them.",
            "In France, a five year old child can buy an alcoholic drink in a bar",
            "Cuba is the only island in the Caribbean to have a railroad.",
            "If you yelled for 8 years, 7 months and 6 days, you would have produced enough sound energy to heat one cup of coffee.",
            "The strongest muscle in proportion to its size in the human body is the tongue.",
            "Every time you lick a stamp, you're consuming 1/10 of a calorie.",
            "The human heart creates enough pressure when it pumps out to the body to squirt blood 30 feet.",
            "Banging your head against a wall uses 150 calories an hour."



    };



    public String getFact() {



        String fact = "";
        //random fact
        Random randomGenerator = new Random();
        int randomNumber = randomGenerator.nextInt(mFacts.length);
        fact = mFacts[randomNumber];

        return fact;


    }
}
